sudo: true
dist: trusty
language: node_js
compiler: [ clang ]
cache: { directories: [ node_modules ] }
node_js: [ '9', '8', '7', '6', '5', '4' ]
addons:
  apt:
    sources: [ boost-latest,  ubuntu-toolchain-r-test ]
    packages: [ g++-4.9, libboost1.55-all-dev ]
os: [ linux, osx ]
before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update
      brew install boost155
    fi
    export PATH=./node_modules/.bin/:$PATH
install:
  - npm install --build-from-source
