sudo: true
dist: trusty
language: node_js
compiler:
  - gcc
cache:
  directories:
    - node_modules
node_js:
  - '5'
  - '4'
  - iojs-v3
  - iojs-v2
  - iojs-v1
addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
